-- Ranking da Liga Brasileira de Futevôlei — temporada 2026
-- Atualizado após etapa de 17/06/2026 (54ª etapa Team Águia Footvolley Cup)
-- Executa no Supabase SQL Editor

-- Limpa dados anteriores da liga (mantém apenas entradas sem instagram/username externo)
TRUNCATE TABLE ranking_individual RESTART IDENTITY;
TRUNCATE TABLE ranking_dupla      RESTART IDENTITY;

-- ────────────────────────────────────────────────
-- RANKING INDIVIDUAL FEMININO
-- ────────────────────────────────────────────────
INSERT INTO ranking_individual (nome, genero, pontos) VALUES
  ('Natalia Guitler', 'feminino', 2700),
  ('Ray',             'feminino', 2700),
  ('Amanda',          'feminino', 2400),
  ('Rafinha',         'feminino', 2400),
  ('Iza Dias',        'feminino', 1200),
  ('Rafa Ganzo',      'feminino', 1200),
  ('Madu',            'feminino', 1100),
  ('Mari Cipriani',   'feminino', 1100),
  ('Lane',            'feminino',  810),
  ('Ana Luiza',       'feminino',  800),
  ('Ju Picianni',     'feminino',  610),
  ('Nila',            'feminino',  610),
  ('Josy',            'feminino',  550),
  ('Vanessa',         'feminino',  500),
  ('Nuala',           'feminino',  160),
  ('Emili',           'feminino',  150),
  ('Aninha',          'feminino',  120),
  ('Livia',           'feminino',  120),
  ('Bella',           'feminino',  110),
  ('May',             'feminino',  110),
  ('Bia Rio',         'feminino',   70),
  ('Lunna',           'feminino',   70),
  ('Mirella',         'feminino',   60),
  ('Sabrina',         'feminino',   30),
  ('Pamela',          'feminino',   30),
  ('Mari Ciasca',     'feminino',   30),
  ('Lorena',          'feminino',   20),
  ('Lana',            'feminino',   20),
  ('Tais',            'feminino',   20),
  ('Monique Gois',    'feminino',   20),
  ('Mari Onda',       'feminino',   20),
  ('Cecília',         'feminino',   10),
  ('Yosy Silva',      'feminino',   10),
  ('Keyla',           'feminino',   10),
  ('Lissa',           'feminino',   10),
  ('Carol',           'feminino',   10),
  ('Malu',            'feminino',   10),
  ('Carioca',         'feminino',   10),
  ('Gabi',            'feminino',   10),
  ('Luana',           'feminino',   10),
  ('Ju Farias',       'feminino',   10),
  ('Mel',             'feminino',   10),
  ('Bella Serafim',   'feminino',   10),
  ('Gabi Parracho',   'feminino',   10);

-- ────────────────────────────────────────────────
-- RANKING INDIVIDUAL MASCULINO
-- ────────────────────────────────────────────────
INSERT INTO ranking_individual (nome, genero, pontos) VALUES
  ('Índio',           'masculino', 6400),
  ('Felipe',          'masculino', 6400),
  ('Tavinho',         'masculino', 3800),
  ('Gui',             'masculino', 3800),
  ('Dudu',            'masculino', 2500),
  ('Arthur',          'masculino', 2500),
  ('Sandrey',         'masculino', 2070),
  ('Michel',          'masculino', 2070),
  ('Beguinha',        'masculino', 1670),
  ('Giovane',         'masculino', 1570),
  ('Brisa',           'masculino', 1510),
  ('Davi',            'masculino', 1270),
  ('Marcola',         'masculino', 1210),
  ('Pedrinho',        'masculino', 1020),
  ('Murilo',          'masculino',  850),
  ('Preto Mágico',    'masculino',  840),
  ('Vitinho',         'masculino',  840),
  ('Rafa Longo',      'masculino',  630),
  ('Tavinho/BA',      'masculino',  620),
  ('Amaury',          'masculino',  620),
  ('Paulinho',        'masculino',  510),
  ('Matteus',         'masculino',  510),
  ('Fernando',        'masculino',  470),
  ('Franklin',        'masculino',  340),
  ('Biel',            'masculino',  330),
  ('Thierry',         'masculino',  310),
  ('Paraná',          'masculino',  310),
  ('Neguebinha',      'masculino',  220),
  ('Felipe Isse',     'masculino',  200),
  ('Joãozinho',       'masculino',  200),
  ('Edson Jr.',       'masculino',  120),
  ('Dudu Andrade',    'masculino',   40),
  ('Pablo',           'masculino',   30),
  ('VT',              'masculino',   30),
  ('Maestro',         'masculino',   30),
  ('Renan Magnano',   'masculino',   30),
  ('Borges',          'masculino',   20),
  ('Lucas Assis',     'masculino',   20),
  ('Gui Nascimento',  'masculino',   20),
  ('Felipe Messias',  'masculino',   20),
  ('Juka',            'masculino',   20),
  ('Netinho',         'masculino',   10),
  ('Bruninho/GO',     'masculino',   10),
  ('Victor Real',     'masculino',   10),
  ('Saldanha',        'masculino',   10),
  ('Gui',             'masculino',   10),
  ('Renan Billy',     'masculino',   10),
  ('Matheusinho',     'masculino',   10),
  ('Iuri',            'masculino',   10),
  ('Muniz',           'masculino',   10),
  ('Vina',            'masculino',   10),
  ('Juan Tubarão',    'masculino',   10),
  ('Bernardo Bulks',  'masculino',   10),
  ('Scarpelli',       'masculino',   10),
  ('Bryan',           'masculino',   10),
  ('Bruno Barros',    'masculino',   10),
  ('Suylan',          'masculino',   10),
  ('Eduzinho',        'masculino',   10),
  ('Neguinho',        'masculino',   10),
  ('Pedrinho/MT',     'masculino',   10),
  ('Rhuan',           'masculino',   10),
  ('Sergyn',          'masculino',   10),
  ('Cassiano',        'masculino',   10),
  ('Savio',           'masculino',   10),
  ('Avatar',          'masculino',   10),
  ('Heytor',          'masculino',   10),
  ('Denner',          'masculino',   10),
  ('Hiltinho',        'masculino',   10),
  ('Lapiseira',       'masculino',   10);

-- ────────────────────────────────────────────────
-- RANKING DUPLAS FEMININO
-- ────────────────────────────────────────────────
INSERT INTO ranking_dupla (atleta1, atleta2, genero, pontos) VALUES
  ('Natalia',    'Ray',          'feminino', 5400),
  ('Rafinha',    'Amanda',       'feminino', 4800),
  ('Iza Dias',   'Rafa Ganzo',   'feminino', 2400),
  ('Maou',       'Mari Cipriani','feminino', 2200),
  ('Lane',       'Ana Luiza',    'feminino', 1610),
  ('Ju Picianni','Nila',         'feminino', 1220),
  ('Josy',       'Vanessa',      'feminino', 1050),
  ('Nuala',      'Emili',        'feminino',  310),
  ('Aninha',     'Livia',        'feminino',  240),
  ('Bella',      'May',          'feminino',  220),
  ('Bia Rio',    'Lunna',        'feminino',  140),
  ('Pamela',     'Mari Ciasca',  'feminino',   60);

-- ────────────────────────────────────────────────
-- RANKING DUPLAS MASCULINO
-- ────────────────────────────────────────────────
INSERT INTO ranking_dupla (atleta1, atleta2, genero, pontos) VALUES
  ('Índio',      'Felipe',       'masculino', 12800),
  ('Tavinho',    'Gui',          'masculino',  7600),
  ('Dudu',       'Arthur',       'masculino',  5000),
  ('Sandrey',    'Michel',       'masculino',  4140),
  ('Beguinha',   'Giovane',      'masculino',  3240),
  ('Brisa',      'Marcola',      'masculino',  2720),
  ('Davi',       'Pedrinho',     'masculino',  2290),
  ('Murilo',     'Preto Mágico', 'masculino',  1690),
  ('Vitinho',    'Longo',        'masculino',  1470),
  ('Tavinho/BA', 'Amaury',       'masculino',  1240),
  ('Paulinho',   'Matteus',      'masculino',  1020),
  ('Paraná',     'Franklin',     'masculino',   640);
