import { redirect } from "next/navigation";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, CheckCircle2, RefreshCw } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { getUserRole, isCeo } from "@/lib/supabase/roles";
import { resolverAlerta, salvarConfiguracaoAlertas, verificarAlertas } from "./actions";

export default async function OperationalAlertsPage() {
  const supabase = await createClient();
  const [{ data: { user } }, role] = await Promise.all([supabase.auth.getUser(), getUserRole(supabase)]);
  if (!user || !isCeo(role)) redirect("/");
  const admin = createAdminClient();
  const [{ data: settings }, { data: alerts }] = await Promise.all([admin.from("operational_alert_settings").select("*").eq("id", 1).maybeSingle(), admin.from("operational_alerts").select("id, kind, severity, title, entity_type, entity_id, detected_at").eq("status", "open").order("detected_at", { ascending: false }).limit(200)]);
  return <div className="w-full space-y-6 px-6 py-8"><Link href="/admin" className="inline-flex items-center gap-1 text-sm text-gray-500"><ArrowLeft className="size-4" />Painel admin</Link><div><h1 className="text-2xl font-semibold text-gray-900">Alertas operacionais</h1><p className="text-sm text-gray-500">Pagamentos parados, falhas financeiras, reembolsos assistidos e repasses recusados.</p></div><form action={salvarConfiguracaoAlertas} className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><h2 className="font-semibold text-gray-900">Configuração</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{[["enabled","Alertas ativos"],["payment_pending_enabled","Pagamento pendente"],["webhook_failed_enabled","Webhook/processamento falho"],["assisted_refund_enabled","Reembolso assistido"],["payout_rejected_enabled","Repasse recusado"]].map(([name,label]) => <label key={name} className="flex items-center gap-2 text-sm text-gray-700"><input type="checkbox" name={name} defaultChecked={Boolean(settings?.[name])} />{label}</label>)}<label className="text-sm text-gray-700">Minutos para considerar pendente<input type="number" min="5" max="1440" name="payment_pending_minutes" defaultValue={settings?.payment_pending_minutes ?? 30} className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2" /></label></div><button className="mt-4 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Salvar configuração</button></form><div className="flex items-center justify-between"><h2 className="font-semibold text-gray-900">Abertos ({alerts?.length ?? 0})</h2><form action={verificarAlertas}><button className="flex items-center gap-1 rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm font-semibold text-gray-700"><RefreshCw className="size-4" />Verificar agora</button></form></div>{alerts?.length ? <div className="space-y-3">{alerts.map((alert) => <article key={alert.id} className={`rounded-2xl bg-white p-4 ring-1 ${alert.severity === "critical" ? "ring-red-200" : "ring-amber-200"}`}><div className="flex items-start justify-between gap-3"><div><h3 className="flex items-center gap-2 font-semibold text-gray-900"><AlertTriangle className={`size-4 ${alert.severity === "critical" ? "text-red-600" : "text-amber-600"}`} />{alert.title}</h3><p className="mt-1 text-xs text-gray-500">{alert.entity_type} · {alert.entity_id.slice(0, 12)} · {new Date(alert.detected_at).toLocaleString("pt-BR")}</p></div><form action={resolverAlerta}><input type="hidden" name="id" value={alert.id} /><button className="flex items-center gap-1 text-xs font-semibold text-emerald-700"><CheckCircle2 className="size-4" />Resolver</button></form></div></article>)}</div> : <p className="rounded-2xl bg-emerald-50 p-5 text-sm text-emerald-800">Nenhum alerta aberto.</p>}</div>;
}
